version: "3"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sqlchallenge
      - POSTGRES_PASSWORD=sqlchallenge
      - POSTGRES_DB=sqlchallenge

volumes:
  postgres_data:
