name: Run Challenge Tests

on:
  push:
    branches: ["**"] # Run on push to any branch
  pull_request:
    branches: [main] # Also run on PRs to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Start database
        run: docker compose up -d

      - name: Wait for database to be ready
        run: |
          # Wait for PostgreSQL to be ready
          timeout=60
          while ! docker exec $(docker ps -q -f name=postgres) pg_isready -U postgres 2>/dev/null; do
            timeout=$((timeout-1))
            if [ $timeout -eq 0 ]; then
              echo "Timeout waiting for PostgreSQL to be ready"
              exit 1
            fi
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done

      - name: Run all challenge tests
        run: |
          python challenge.py --test-all
